package com.bitlabs.App.Entity;

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToMany;
import lombok.Data;

@Data
@Entity
public class ApplicantSkills {
	
	@Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;  // This ID will be generated by Hibernate

    private String skillName;
    double experience;

    // Define the ManyToMany relationship with ApplicantProfile
    @ManyToMany(fetch = FetchType.LAZY,
		      cascade = {
		              CascadeType.PERSIST,
		              CascadeType.MERGE
		          })
    @JsonIgnore
    private Set<ApplicantProfile> applicantProfiles = new HashSet<>();

}
